- name: vyos blue10 net config
  hosts: vyos
  tasks:
  - name: configure vyos dhcp
    vyos_config:
      save: yes
      lines:
        - set service dhcp-server global-parameters 'local-address {{ lan_ip }};'
        - set service dhcp-server shared-network-name {{ network_name }} authoritative
        - set service dhcp-server shared-network-name {{ network_name }} subnet {{ lan }} default-router '{{ lan_ip }}'
        - set service dhcp-server shared-network-name {{ network_name }} subnet {{ lan }} name-server '{{ dhcp_name_server }}'
        - set service dhcp-server shared-network-name {{ network_name }} subnet {{ lan }} domain-name '{{ domain_name }}'
        - set service dhcp-server shared-network-name {{ network_name }} subnet {{ lan }} lease '86400'
        - set service dhcp-server shared-network-name {{ network_name }} subnet {{ lan }} range {{ network_name }}-POOL start '10.0.5.75'
        - set service dhcp-server shared-network-name {{ network_name }} subnet {{ lan }} range {{ network_name }}-POOL stop '10.0.5.125'
