all:
  hosts:
    rocky1:
      ansible_host: 10.0.5.75
      hostname: rocky1
      lan_ip: 10.0.5.10
    rocky2:
      ansible_host: 10.0.5.77
      hostname: rocky2
      lan_ip: 10.0.5.11
    rocky3:
      ansible_host: 10.0.5.76
      hostname: rocky3
      lan_ip: 10.0.5.12
  vars:
    ansible_user: champuser
    gateway: 10.0.5.2
    name_server: 10.0.5.5
    device: ens192
    public_key: ""
