servers:
  hosts:
    dc-blue1:
      ansible_host: 10.0.5.5
      ansible_user: Administrator
      ansible_password: "Ch@mpl@1n!25"
      ansible_connection: winrm
      ansible_port: 5985
    fs-blue1:
      ansible_host: 10.0.5.215
      ansible_user: Administrator
      ansible_password: "Ch@mpl@1n!25"
      ansible_connection: winrm
      ansible_port: 5985
    win-wks:
      ansible_host: 10.0.5.82
      ansible_user: Administrator
      ansible_password: "Ch@mpl@1n!25"
      ansible_connection: winrm
      ansible_port: 5985    